pipeline:
  name: TestPipeline
  identifier: TestPipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "Hello world"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
                  enforce:
                    policySets:
                      - Test1
        tags: {}
  notificationRules:
    - name: testNotify
      identifier: testNotify
      pipelineEvents:
        - type: PipelineFailed
        - type: PipelineSuccess
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - trupti.bhat@slkgroup.com
      enabled: true
