apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: SampleDeployJob
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/TruptiBhat/SampleDeployJob
